# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:44
from __future__ import unicode_literals
import os.path
from django.db import migrations
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'municipios.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)

def unload_fixtures(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)


class Migration(migrations.Migration):
    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=load_fixture, reverse_code=unload_fixtures, atomic=True)
    ]
